### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by Ahmed-Ghobashi** [rs239/velorama#3]
Thank you for this package, I tried installing Velorama using
 pip install velorama

But I get this error: 
error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\ahmed\AppData\Local\Temp\pip-install-sgrrhble\sklearn_fa38950c8574492da0c4cb7e252dd14d\setup.py", line 10, in <module>
      LONG_DESCRIPTION = f.read()
    File "C:\Users\ahmed\miniconda3\envs\my_project\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

##
I tried to upgrade pip, wheel, setuptools, but it didn't work.
Any help will be appreciated
Thank you

**Comment by Ahmed-Ghobashi** [comment]
I solved the problem by installing sklearn 0.0
pip install sklearn==0.0
followed by
pip install velorama

**Comment by Ahmed-Ghobashi** [comment]
I solved the problem by installing sklearn 0.0
pip install sklearn==0.0
followed by
pip install velorama
